### PR TITLE
Korean Translations

### PR DESCRIPTION
**Pull request by ccho-qk4**
I tried my best.

### CODE REVIEW

**Comment by boo-dev** [comment]
@RussianBabushka Thank you!! Before I can merge the pull request, you have to make a new folder called ko.lproj and put the Prefs.strings file in there instead of en.lproj :)

**Comment by ccho-qk4** [comment]
@boo-dev ok, I think I fixed it. I'm a complete noob to GitHub so I apologize for my ignorance😅

**Comment by boo-dev** [comment]
@RussianBabushka do you have a twitter that I can put in the credits for translating?

**Comment by ccho-qk4** [comment]
@boo-dev sure. @calebcho8 will do

**Comment by boo-dev** [comment]
@RussianBabushka I just pushed a few more strings to the base localization file if you don't mind updating your translations to support them :)

**Comment by ccho-qk4** [comment]
@boo-dev Done :)

**Comment by boo-dev** [comment]
@RussianBabushka pushed a few final strings that need translating, there's a few more lines at the end of prefs.plist and there's a few extra in credits.plist , Thanks again :)

**Comment by ccho-qk4** [comment]
@boo-dev done.

**Pull request merged**
